### ISSUE TITLE
java module is not supported

### ISSUE THREAD

**Issue by vlebedynskyi** [adwiv/android-fat-aar#14]
First of all thanks for your work

I try to use  embedded project(':EAPI') where is EAPI is my **Java** module and it **fails** on parsing of **AndroidManifest** file because **java** project **doesn't have it.**
I think it is great idea to add this functionality
Logs:
```
FAILURE: Build failed with an exception.

* Where:
Script '/Users/vitalii_lebedynskyi/Projects/MyProject/mainModule/fat-aar.gradle' line: 234

* What went wrong:
Execution failed for task ':sdk:embedRClassFiles'.
> /Users/vitalii_lebedynskyi/Projects/MyProject/mainModule/sdk/build/intermediates/exploded-aar/com.package.eapi/EAPI/1.00/AndroidManifest.xml (No such file or directory)
```

**Comment by adwiv** [comment]
Haven't used java modules but I believe they would simply generate jar files which will not be "exploded".

I will test it out when I get some free time.

Thanks.

**Comment by adwiv** [comment]
Fixed in current release
