### ISSUE TITLE
How do I obfuscate the merged AAR?

### ISSUE THREAD

**Issue by b95505017** [adwiv/android-fat-aar#16]
It seems like turn on `minifyEnabled` is not working, I'll get lot's of `duplicate definition of library class` and the output class.jar lost most of the codes.

**Comment by adwiv** [comment]
Where do you get duplicate definition - while compiling the library or
while compiling the app?

Also does if work properly without minify enabled?

**Comment by b95505017** [comment]
Sorry I found this may be false alarm.
The real issue is that `task embedProguard` can't find `proguardLibFile` at first, I have to type twice `assembleRelease` so that `proguardLibFile.exists()` become `true`.
It means that AAR's dependencies's `consumerProguardFiles` doesn't include correctly if I did clean release build.
