### ISSUE TITLE
How to merge excluded dependencies declared in embedded modules?

### ISSUE THREAD

**Issue by b95505017** [adwiv/android-fat-aar#17]
In publish.gradle only contain ResolvedDependency
`Map<String, ResolvedDependency> depList = new LinkedHashMap<>();`

It doesn't contain exclude rules, how to I include those rules in my embedded modules?
Thanks.

**Comment by adwiv** [comment]
Gradle dependency system is too complex and I don't have much experience with it. 

The configurations object includes a getExcludeRules method. You may try to use it and if it works submit a pull request :)

Cheers.
