### ISSUE TITLE
unable to resolve class MergingReport.Result 

### ISSUE THREAD

**Issue by ruijun** [adwiv/android-fat-aar#20]
@adwiv 
When I use `fat-aar.gradle`, it occurred this error: "unable to resolve class MergingReport.Result "

My project configuration：
* Gradle v2.12. 
* compileSdkVersion 22
* buildToolsVersion "22.0.1"
* com.android.tools.build:gradle:2.0.0

**Comment by slavasav** [comment]
Same here, gradle v 2.12

**Comment by adwiv** [comment]
Fixed in latest release. Kindly test.
