### ISSUE TITLE
packageReleaseJniLibs not found error

### ISSUE THREAD

**Issue by Ohana35** [adwiv/android-fat-aar#21]
After upgrading to Gradle 2.10 the following line:

embedJniLibs.mustRunAfter packageReleaseJniLibs

no longer compiles and causes an error in Android Studio. Have to comment it out to get the code to compile now

**Comment by Ohana35** [comment]
<img width="583" alt="screen shot 2016-04-22 at 10 54 21 pm" src="https://cloud.githubusercontent.com/assets/6379965/14759595/2cf92f96-08dd-11e6-8db5-888df9106a6d.png">
<img width="482" alt="screen shot 2016-04-22 at 10 54 11 pm" src="https://cloud.githubusercontent.com/assets/6379965/14759596/2cf9e382-08dd-11e6-9bea-af8114d48583.png">

**Comment by ikabar** [comment]
Having the same issue.

**Comment by parizene** [comment]
add this code instead of old one
`if (tasks.findByPath('packageReleaseJniLibs') != null) {
    embedJniLibs.mustRunAfter packageReleaseJniLibs
} else if (tasks.findByPath('mergeReleaseJniLibFolders') != null) {
    embedJniLibs.mustRunAfter mergeReleaseJniLibFolders
}`

**Comment by ikabar** [comment]
It solved this issue but I'm now getting
`Error:Could not find property 'compileReleaseJava' on project ':myproject'.`
