### ISSUE TITLE
Unable to embed thirdparty library into the aar

### ISSUE THREAD

**Issue by chamugoli** [adwiv/android-fat-aar#22]
embedded project('io.socket:socket.io-client:0.7.0'), added this to my module dependencies, this is not being added to the aar
Seeing this error:
Error:(29, 0) Project with path 'io.socket:socket.io-client:0.7.0' could not be found in project ':test'

Please let me know if this is not the right approach

Thanks in advance

**Comment by DenisMondon** [comment]
Hi!

Replace by this:
`embedded 'io.socket:socket.io-client:0.7.0'`
