### ISSUE TITLE
Suggest not merge jars into classes.jar

### ISSUE THREAD

**Issue by l465659833** [adwiv/android-fat-aar#24]
When use proguard, it would be better to leave the jars in the libs directory, rather than merge them into classes.jar in the aar.
Because when we provide the aar, and the users use the same jar with another version , he can replace them as follow:
compile(name: 'mylib', ext: 'aar') {
        exclude group: 'com.android.support', module: 'support-v4'
    }
When users use proguard, they can use as follow:
-libraryjars libs/log4j.jar

ps , please forgive my bad English.

**Comment by adwiv** [comment]
Fixed in current release. We simply copy the included jars in libs directory to the libs directory of the fat-aar file. Although its a better practice to use gradle dependencies instead of bundling jars. 

Cheers.
