### ISSUE TITLE
The Script fails with Gradle 2.2.0 / Android Studio 2.2 / Build tools 24.0.2

### ISSUE THREAD

**Issue by manjia** [adwiv/android-fat-aar#30]
After confirming that updating Android Studio / Gradle / Build tools causes my project to not being able any longer to deploy a fat aar I tested the script on a newly created basic project shrinked down to the bones and it still keeps failing.

The test project is structured as follows:

- "library1" contains one class, "MyClass1" which contains a string "public String myString = "MyStringTest";"
- "library2" contains one class, "MyClass2" which EXTENDS "MyClass1" and logs myString within its constructor.

both projects are 'com.android.library's 

library1's gradle is configured as follow:

```
apply plugin: 'com.android.library'
android {
    compileSdkVersion 24
    buildToolsVersion "24.0.2"
    defaultConfig {
        minSdkVersion 15
        targetSdkVersion 24
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}
```

library2's gradle is configured as follow:

```
apply plugin: 'com.android.library'

android {
    compileSdkVersion 24
    buildToolsVersion "24.0.2"
    defaultConfig {
        minSdkVersion 15
        targetSdkVersion 24
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

apply from: 'https://raw.githubusercontent.com/adwiv/android-fat-aar/master/fat-aar.gradle'

dependencies {
    embedded project(':library1')
}
```

running an "assembleRelease" leads to this result:

```
[...]
:app:generateXClass
Note: there were 4 duplicate class definitions.
      (http://proguard.sourceforge.net/manual/troubleshooting.html#duplicateclass)
Warning: library class net.mylibrary2.MyClass2 extends or implements program class net.mylibrary1.MyClass1
Warning: there were 1 instances of library classes depending on program classes.
         You must avoid such dependencies, since the program classes will
         be processed, while the library classes will remain unchanged.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#dependency)
:app:generateXClass FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:generateXClass'.
> java.io.IOException: Please correct the above warnings first.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

after some googling I saw some people saying that the warning can be solved by adding this to ProGuard:

```
-keep class net.library1.** { *; }
-dontwarn net.library1.**
```

however I tryied this and it doesn's seem to work, neither does ignoring lint warnings like this:

```
    lintOptions {
        abortOnError false
    }

```

so I tryied to take a look at the fat-aar script and I found out that using keep / dontwarn inside the task generateXClass lets somehow the build finish without errors:

```
task generateXClass(type: ProGuardTask, dependsOn: generateRClass) {

    [...]
    dontwarn 'net.library1.**'
    keep 'class net.library1.** { *; }'
    [...]

}
```

however this way the library1 is NOT INCLUDED in the final .aar

At this point I don't have enough gradle build knowledge to go on with further debugging...

**Comment by adwiv** [comment]
Thanks, I'll check it tomorrow.

It will be great if you can attach the minimal project zip so that I can
check faster.

**Comment by manjia** [comment]
Here it is: [FataarTest.zip](https://github.com/adwiv/android-fat-aar/files/496262/FataarTest.zip)

MyLibrary2 is the main project

Thank You

**Comment by adwiv** [comment]
Thanks.. I could replicate the issue and it seems to be fixed with the latest version.
Kindly test and let me know.

**Comment by manjia** [comment]
You are right, I just tested it again with the latest script version and the build completes succesfully!

Thanks again!
