### ISSUE TITLE
Error when "apply from: fat-aar.gradle" but not using "embedded"

### ISSUE THREAD

**Issue by isometriq** [adwiv/android-fat-aar#36]
Error:Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
FAILURE: Build failed with an exception.

* Where:
Script '*****\fat-aar.gradle' line: 294

* What went wrong:
Execution failed for task ':myproject:generateRJava'.
> *****\build\fat-aar\release\mapping-r.txt (The system cannot find the path specified)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by adwiv** [comment]
Thanks.. Fixed by adding tasks only if embedded dependencies exist.
