### ISSUE TITLE
android.compileSdkVersion is missing!

### ISSUE THREAD

**Issue by seedinwind** [adwiv/android-fat-aar#39]
when I use the fat-aar.gradle in my project,it reports: android.compileSdkVersion is missing!
`apply plugin: 'com.android.application'
apply plugin: 'checkstyle'
 apply from: 'fat-aar.gradle'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.2"`
I have to put the apply statement below compileSdkVersion like 
`apply plugin: 'com.android.application'
apply plugin: 'checkstyle'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.2"
    apply from: 'fat-aar.gradle'
`
my android studio version is 2.2

**Comment by adwiv** [comment]
This issue would no longer be there with the latest release where we have removed the internal proguard. The issue occured because proguard tried to use android boot classpath which did not exist without sdkVersion being defined.

Cheers.
