### ISSUE TITLE
Could not find property 'proguardRelease'

### ISSUE THREAD

**Issue by puretekniq** [adwiv/android-fat-aar#4]
In 1.2.3, it appears there is no proguardRelease task. I commented this out as I'm not using proguard at this stage, but FYI.

**Comment by Nachbar90** [comment]
First of all, great plugin (even if it doesn´t work). I can´t get why there is no support for multi library projects from scratch. But are there any news about this?

**Comment by adwiv** [comment]
proguradRelease is only used when you set minify = true in the build
Fixed in the latest release by adding a conditional check.
