### ISSUE TITLE
com.android.dex.DexException: Multiple dex files define Lcom/android/submodule/BuildConfig;

### ISSUE THREAD

**Issue by mklueh** [adwiv/android-fat-aar#51]
I´m using fat-aar to merge six modules, which are forming my library I´m exporting. In addition, I have an application module in my project to test the library.

> Error:Execution failed for task ':TestApp:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: 
> com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: 
> com.android.dex.DexException: Multiple dex files define Lcom/android/submodule/BuildConfig;

I was using an older fat-aar version before (0.1) I think, together with gradle 1.2.3 and build-tools 23.0.3, which worked perfectly. But with the current version of both my test application is unusable.

Has anyone experienced similar issues?

**Comment by lijunjieone** [comment]
I have same issue.

**Comment by Mklueh** [comment]
I have now managed to get the BuildConfig error away by removing cycling module inclusions temporarily, but now I´m getting the same error with my own classes of my submodule. The simplified hierarchy consists now just of one application, the library module and one submodule.

**Comment by talobin** [comment]
I have the same issue and the work-around for me right now is to enable multidex in the build.gradle of whichever module it is complaining.
