### ISSUE TITLE
Error:Could not get unknown property 'packageReleaseResources' for projectof type org.gradle.api.Project.

### ISSUE THREAD

**Issue by lichens1** [adwiv/android-fat-aar#56]
apply from: 'https://raw.githubusercontent.com/adwiv/android-fat-aar/master/fat-aar.gradle'

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.1.1'
    testCompile 'junit:junit:4.12'
    embedded project(':libcamera-release')
    embedded project(':libcommon-release')
    embedded project(':libidcardcaptor-release')
    embedded project(':libimagecapture-release')
    embedded project(':liblivenessdetectionview2-release')
    embedded project(':liblivenessdetector2-release')
    embedded project(':olivelibrary')
}

**Comment by liangxianshen** [comment]
The same problem, how do you solve？

**Comment by lichens1** [comment]
I don't know if you can read Chinese , But it has a solution     
http://www.jianshu.com/p/19228d835e68

**Comment by liangxianshen** [comment]
@lichens1 老乡！
