### ISSUE TITLE
Can I embed local .aar libraries?

### ISSUE THREAD

**Issue by fgsantoyo** [adwiv/android-fat-aar#8]
Hi Adwiv, 

I have custom libraries packaged as aar that I'd like to include in my fat aar. Is this supported by this script?

Thanks,

Fernando

**Comment by adwiv** [comment]
Are they in the local filesystem? Where are they placed? How do you include
these aar files as dependencies?

**Comment by fgsantoyo** [comment]
Right now they are in my libs folder and included like the following
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar']) 
    //... other dependencies
    compile 'com.enterprise.android.common:common@aar'
}

**Comment by adwiv** [comment]
If it is included like this, it should probably work. I haven't tried
myself this way although. Do you get any issues?

**Comment by adwiv** [comment]
The correct way to embed local aar files is to import them as a separate module in the project. 
File -> New Module -> Import Jar/AAR file
Closing the issue.
