### ISSUE TITLE
Doesn't work with new Android Gradle 3.0 plugin

### ISSUE THREAD

**Issue by uberbinge** [adwiv/android-fat-aar#81]
I am using new Android studio 3.0, and migrating gradle scripts to 3.0 according to migration guide provided [here](https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html#variant_api)

The latest master of fataar.gradle compiles fine, but when I actually change dependencies to embedded and run assembleRelease I get following errors for each dependent module.

`Could not resolve project :module-a.
    Required by:
        project :main-module
     > Cannot choose between the following configurations of project :module-a:
         - debugApiElements
         - debugRuntimeElements
         - releaseApiElements
         - releaseRuntimeElements
       All of them match the consumer attributes:
         - Configuration 'debugApiElements':
             - Found com.android.build.api.attributes.BuildTypeAttr 'debug' but wasn't required.
             - Found com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' but wasn't required.
             - Found com.android.build.gradle.internal.dependency.VariantAttr 'debug' but wasn't required.
             - Found org.gradle.api.attributes.Usage 'java-api' but wasn't required.
         - Configuration 'debugRuntimeElements':
             - Found com.android.build.api.attributes.BuildTypeAttr 'debug' but wasn't required.
             - Found com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' but wasn't required.
             - Found com.android.build.gradle.internal.dependency.VariantAttr 'debug' but wasn't required.
             - Found org.gradle.api.attributes.Usage 'java-runtime' but wasn't required.
         - Configuration 'releaseApiElements':
             - Found com.android.build.api.attributes.BuildTypeAttr 'release' but wasn't required.
             - Found com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' but wasn't required.
             - Found com.android.build.gradle.internal.dependency.VariantAttr 'release' but wasn't required.
             - Found org.gradle.api.attributes.Usage 'java-api' but wasn't required.
         - Configuration 'releaseRuntimeElements':
             - Found com.android.build.api.attributes.BuildTypeAttr 'release' but wasn't required.
             - Found com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' but wasn't required.
             - Found com.android.build.gradle.internal.dependency.VariantAttr 'release' but wasn't required.
             - Found org.gradle.api.attributes.Usage 'java-runtime' but wasn't required.`

I have following versions of Gradle and build tools:
`androidGradlePlugin: '3.0.0-beta6',
buildTools         : '26.0.1',
distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-all.zip`

**Comment by jolly336** [comment]
@waah42 I also get this error,have you solved this?

**Comment by uberbinge** [comment]
@haoxunwang sadly not yet 😞 ,

**Comment by Sarubbaru** [comment]
+1

**Comment by taojiujiu** [comment]
+1

**Comment by genamendola17** [comment]
+1

**Comment by tetnic** [comment]
+1

**Comment by lgengsy** [comment]
+1

**Comment by Sarubbaru** [comment]
+1

**Comment by frenk91** [comment]
+1

**Comment by SalvatoreZuardi** [comment]
+1

**Comment by iastemesem** [comment]
+1

**Comment by uberbinge** [comment]
As i see new people also looking for the solution, please star this issue on official google issue tracker||https://issuetracker.google.com/issues/62121508

**Comment by mengchaoshen** [comment]
+1

**Comment by deng0515001** [comment]
＋１

**Comment by deng0515001** [comment]
@waah42 I also get this error,have you solved this?

**Comment by wnchen** [comment]
+1

**Comment by byhook** [comment]
建议大家用gradle 2.2.3插件版本
可以看下我踩过的坑
https://juejin.im/post/5b28672bf265da59645b031a

**Comment by AvivVegh** [comment]
+1
